In [1]:
import pandas as pd

In [13]:
partial_results = pd.read_csv('retrieval_results_dublicates.csv')
all_judgments = pd.read_csv('all_judgments.csv')
sql_big_llm_res = pd.read_csv('retrieval_sql_hr_bigger_llm.csv')
rag_agent_res = pd.read_csv('retrieval_rag_agent.csv')
gold_subset = pd.read_csv('gold_subset.csv')

In [15]:
all_retrieval_results = pd.concat([partial_results, sql_big_llm_res, rag_agent_res], ignore_index=True)
all_retrieval_results

,query_id,candidate_id,search_system,rank,score,latency_ms,retrieved_at,latency_to_first_ms
0,Q_00001,C_37247,bm25,1.0,0.364034,596.772841,2026-03-29T21:12:23.995159,NaN
1,Q_00001,C_30277,bm25,2.0,0.363219,596.772841,2026-03-29T21:12:23.995159,NaN
2,Q_00001,C_32912,bm25,3.0,0.363181,596.772841,2026-03-29T21:12:23.995159,NaN
3,Q_00001,C_03026,bm25,4.0,0.361167,596.772841,2026-03-29T21:12:23.995159,NaN
4,Q_00001,C_27387,bm25,5.0,0.360851,596.772841,2026-03-29T21:12:23.995159,NaN
...,...,...,...,...,...,...,...,...
11819,Q_00141,C_40625,agent_rag,11.0,0.680000,32256.135195,2026-04-06T12:48:05.181674,NaN
11820,Q_00141,C_31132,agent_rag,12.0,0.650000,32256.135195,2026-04-06T12:48:05.181674,NaN
11821,Q_00141,C_19448,agent_rag,13.0,0.620000,32256.135195,2026-04-06T12:48:05.181674,NaN
11822,Q_00141,C_26396,agent_rag,14.0,0.580000,32256.135195,2026-04-06T12:48:05.181674,NaN
11823,Q_00141,C_07595,agent_rag,15.0,0.550000,32256.135195,2026-04-06T12:48:05.181674,NaN

In [16]:
all_retrieval_results = all_retrieval_results.merge(gold_subset[['query_id', 'is_gold']], on='query_id', how='left')

In [11]:
final_df = all_retrieval_results.merge(
    all_judgments[['query_id', 'candidate_id', 'relevance_score', 'judge_comment']],
    on=['query_id', 'candidate_id'],
    how='left'
)
final_df

,query_id,candidate_id,search_system,rank,score,latency_ms,retrieved_at,latency_to_first_ms,is_gold,relevance_score,judge_comment
0,Q_00001,C_37247,bm25,1.0,0.364034,596.772841,2026-03-29T21:12:23.995159,NaN,True,0.0,"Отсутствие Python, FastAPI/Django и несоответс..."
1,Q_00001,C_30277,bm25,2.0,0.363219,596.772841,2026-03-29T21:12:23.995159,NaN,True,0.0,Отсутствие ключевого стэка (Python/FastAPI/Dja...
2,Q_00001,C_32912,bm25,3.0,0.363181,596.772841,2026-03-29T21:12:23.995159,NaN,True,0.0,Кандидат не имеет опыта в Python и не соответс...
3,Q_00001,C_03026,bm25,4.0,0.361167,596.772841,2026-03-29T21:12:23.995159,NaN,True,0.0,"Отсутствие опыта в Python, FastAPI/Django. Клю..."
4,Q_00001,C_27387,bm25,5.0,0.360851,596.772841,2026-03-29T21:12:23.995159,NaN,True,0.0,Кандидат не соответствует должности (сетевой а...
...,...,...,...,...,...,...,...,...,...,...,...
11819,Q_00141,C_40625,agent_rag,11.0,0.680000,32256.135195,2026-04-06T12:48:05.181674,NaN,NaN,NaN,NaN
11820,Q_00141,C_31132,agent_rag,12.0,0.650000,32256.135195,2026-04-06T12:48:05.181674,NaN,NaN,NaN,NaN
11821,Q_00141,C_19448,agent_rag,13.0,0.620000,32256.135195,2026-04-06T12:48:05.181674,NaN,NaN,NaN,NaN
11822,Q_00141,C_26396,agent_rag,14.0,0.580000,32256.135195,2026-04-06T12:48:05.181674,NaN,NaN,NaN,NaN
11823,Q_00141,C_07595,agent_rag,15.0,0.550000,32256.135195,2026-04-06T12:48:05.181674,NaN,NaN,NaN,NaN