# data

In [10]:
import pandas as pd
candidates_small = pd.read_csv('raw/candidates_small.csv')
candidates_full = pd.read_csv('raw/candidates_full_raw.csv')
candidates = pd.read_csv('raw/candidates.csv')

In [11]:
candidates.columns

Index(['candidate_id', 'sex', 'age', 'expected_salary_rub', 'desired_position',
       'city', 'ready_to_relocate', 'ready_for_business_trips',
       'employment_type', 'work_schedule', 'work_experience',
       'work_experience_years', 'last_company', 'last_job_title',
       'education_level_and_university', 'resume_updated_at', 'has_car'],
      dtype='object')

In [12]:
candidates_small.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4951 entries, 0 to 4950
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   candidate_id                    4951 non-null   object
 1   sex                             4951 non-null   object
 2   age                             4951 non-null   int64
 3   expected_salary_rub             4951 non-null   int64
 4   desired_position                4951 non-null   object
 5   city                            4951 non-null   object
 6   ready_to_relocate               4853 non-null   object
 7   ready_for_business_trips        4939 non-null   object
 8   employment_type                 4951 non-null   object
 9   work_schedule                   4951 non-null   object
 10  work_experience                 4928 non-null   object
 11  last_company                    4951 non-null   object
 12  last_job_title                  4951 non-null   object
 13  education_level_and_university  4951 non-null   object
 14  resume_updated_at               4951 non-null   object
 15  has_car                         4951 non-null   bool
dtypes: bool(1), int64(2), object(13)
memory usage: 585.2+ KB

In [13]:
candidates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   candidate_id                    44744 non-null  object
 1   sex                             44744 non-null  object
 2   age                             44744 non-null  int64
 3   expected_salary_rub             44744 non-null  int64
 4   desired_position                44744 non-null  object
 5   city                            44744 non-null  object
 6   ready_to_relocate               43915 non-null  object
 7   ready_for_business_trips        44668 non-null  object
 8   employment_type                 44744 non-null  object
 9   work_schedule                   44744 non-null  object
 10  work_experience                 44576 non-null  object
 11  work_experience_years           44574 non-null  float64
 12  last_company                    44743 non-null  object
 13  last_job_title                  44742 non-null  object
 14  education_level_and_university  44744 non-null  object
 15  resume_updated_at               44744 non-null  object
 16  has_car                         44744 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(13)
memory usage: 5.5+ MB

In [15]:
candidates.head()

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
0,C_00001,Мужчина,39,29000,Системный администратор,Советск (Калининградская область),False,False,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,16.833333,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,2019-04-16 15:59:00,True
1,C_00002,Мужчина,60,40000,Технический писатель,Королев,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,19.416667,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,2019-04-12 08:42:00,False
2,C_00003,Женщина,36,20000,Оператор,Тверь,False,False,полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,10.250000,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,2019-04-16 08:35:00,False
3,C_00004,Мужчина,38,100000,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Саратов,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,18.750000,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,2019-04-08 14:23:00,False
4,C_00005,Женщина,26,140000,Региональный менеджер по продажам,Москва,False,True,полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,5.583333,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,2019-04-22 10:32:00,False

In [13]:
print(candidates_small['work_experience'].iloc[0])

Опыт работы 16 лет 10 месяцев  Август 2010 — по настоящее время 8 лет 10 месяцев МАОУ "СОШ № 1 г.Немана" Системный администратор Обслуживание ПК,установка ПО, ремонт, периферийной техники, Интернет локальная сеть. Ведение Электронного журнала, сайта организации.  Август 2002 — Август  2010 8 лет 1 месяц ТС "ВЕСТЕР-ИНФО" Старший продавец, директор отдела Продажи компьютерной техники

In [14]:
candidates_small.head(2)

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
0,C_00001,Мужчина,39,29000,Системный администратор,Советск (Калининградская область),False,False,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,2019-04-16 15:59:00,True
1,C_00002,Мужчина,60,40000,Технический писатель,Королев,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,2019-04-12 08:42:00,False

In [18]:
candidates_full['Командировки'].unique()

array(['не готов к командировкам', 'готов к редким командировкам',
       'не готова к командировкам', 'готова к командировкам',
       'готов к командировкам', 'готова к редким командировкам', nan],
      dtype=object)

In [10]:
candidates_full.head()

,candidate_id,Пол,Возраст,Дата рождения,ЗП,Ищет работу на должность:,Город,Переезд,Командировки,Занятость,График,Опыт работы (лет),Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,C_00001,Мужчина,39,27-11-1979,29000,Системный администратор,Советск (Калининградская область),не готов к переезду,не готов к командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",16.83,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,C_00002,Мужчина,60,20-03-1959,40000,Технический писатель,Королев,не готов к переезду,готов к редким командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",19.42,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,C_00003,Женщина,36,12-08-1982,20000,Оператор,Тверь,не готова к переезду,не готова к командировкам,полная занятость,полный день,10.25,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,C_00004,Мужчина,38,25-06-1980,100000,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Саратов,не готов к переезду,готов к редким командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",18.75,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,C_00005,Женщина,26,03-03-1993,140000,Региональный менеджер по продажам,Москва,не готова к переезду,готова к командировкам,полная занятость,полный день,5.58,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

In [4]:
candidates_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 17 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   candidate_id                     44744 non-null  object
 1   Пол                              44744 non-null  object
 2   Возраст                          44744 non-null  int64
 3   Дата рождения                    44744 non-null  object
 4   ЗП                               44744 non-null  object
 5   Ищет работу на должность:        44744 non-null  object
 6   Город                            44744 non-null  object
 7   Переезд                          44744 non-null  object
 8   Командировки                     44668 non-null  object
 9   Занятость                        44744 non-null  object
 10  График                           44744 non-null  object
 11  Опыт работы (лет)                44574 non-null  float64
 12  Последнее/нынешнее место работы  44743 non-null  object
 13  Последняя/нынешняя должность     44742 non-null  object
 14  Образование и ВУЗ                44744 non-null  object
 15  Обновление резюме                44744 non-null  object
 16  Авто                             44744 non-null  object
dtypes: float64(1), int64(1), object(15)
memory usage: 5.8+ MB

In [6]:
candidates_full['Авто'].unique()

array(['Имеется собственный автомобиль', 'Не указано'], dtype=object)

In [1]:
import pandas as pd

In [35]:
candidates = pd.read_csv('raw/candidates.csv')
candidates.insert(0, "candidate_id", [f"C_{i:05d}" for i in range(1, len(candidates) + 1)])
candidates.to_csv('raw/candidates.csv', index=False)

In [34]:
candidates

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
0,C_00001,Мужчина,39,29000,Системный администратор,Советск (Калининградская область),False,False,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,2019-04-16 15:59:00,True
1,C_00002,Мужчина,60,40000,Технический писатель,Королев,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,2019-04-12 08:42:00,False
2,C_00003,Женщина,36,20000,Оператор,Тверь,False,False,полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,2019-04-16 08:35:00,False
3,C_00004,Мужчина,38,100000,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Саратов,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,2019-04-08 14:23:00,False
4,C_00005,Женщина,26,140000,Региональный менеджер по продажам,Москва,False,True,полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,2019-04-22 10:32:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,C_04947,Мужчина,29,150000,Системный администратор Linux/DevOps,Москва,False,True,полная занятость,полный день,Опыт работы 6 лет 7 месяцев Июнь 2018 — по на...,"ООО ""Спорт-Экспресс Информ""",Системный администратор,Высшее образование 2015 Московский государств...,2019-04-21 22:18:00,True
4947,C_04948,Женщина,53,20000,Оператор на телефоне,Чебоксары,False,False,частичная занятость,"гибкий график, удаленная работа",Опыт работы 22 года 2 месяца Март 2005 — по н...,Салон красоты АНЮТА,Администратор салона красоты,Среднее специальное образование 1986 Строитель...,2019-04-18 21:08:00,False
4948,C_04949,Мужчина,22,100000,Тестировщик на проникновение / Тестировщик вэб...,Москва,False,False,полная занятость,"гибкий график, полный день",Опыт работы 3 месяца Июнь 2017 — Август 2017...,"ООО ""ГНСС плюс""",Технический специалист,Высшее образование (Магистр) 2019 University o...,2019-04-19 18:33:00,True
4949,C_04950,Мужчина,38,170000,руководитель ИТ-подразделения,Казань,True,True,полная занятость,полный день,Опыт работы 16 лет 9 месяцев Март 2017 — по н...,ICL-КПО ВС,Системный архитектор / заместитель техническог...,Высшее образование 2003 Казанский национальны...,2019-05-07 11:54:00,False
4950,C_04951,Мужчина,23,50000,Менеджер проектов,Москва,False,False,"стажировка, проектная работа, полная занятость","гибкий график, полный день, сменный график, уд...",Опыт работы 1 год 10 месяцев Октябрь 2018 — п...,Экспримо,Проектный менеджер,Неоконченное высшее образование 2018 Военный ...,2019-04-17 10:42:00,False

In [29]:
candidates

In [3]:
data = pd.read_csv('raw/dataset_kmu.csv')

In [4]:
data.head()

,Unnamed: 0,должность,город,зарплата,валюта зарплаты,зарплата за период времени,занятость,формат работы,часы работы,график по дням,опыт работы,требования,обязанности,domen,strict,normal,fuzzy,complex
0,0,Backend-разработчик,Зеленоград,не указано,не указано,не указано,Полная занятость,На месте работодателя,8 часов,5/2,От 1 года до 3 лет,1. Опыт работы с Python от 2х лет. 2. Знание и...,1. Разработка и поддержка <highlighttext>backe...,backend,"Backend-разработчик, Python 2+, FastAPI/Django...",Backend-разработчик на Python (FastAPI/Django)...,"Опытный разработчик с Python и фреймворками, г...",Разработчик backend-компонентов с опытом 1-3 л...
1,1,Бэкенд разработчик,Москва,140000,RUR,За месяц,Полная занятость,"Удалённо, Гибрид",8 часов,5/2,От 1 года до 3 лет,<highlighttext>Backend</highlighttext>: Python...,Разработка и поддержка <highlighttext>backend<...,backend,"Бэкенд разработчик, Python (FastAPI/Django/Fla...",Backend-разработчик на Python (FastAPI/Django)...,Сильный бэкенд-разработчик с опытом в Python и...,"Бэкенд-разработчик с опытом 1-3 лет, интеграци..."
2,2,Kotlin backend developer (Java),Воронеж,не указано,не указано,не указано,Полная занятость,Удалённо,8 часов,5/2,От 3 до 6 лет,Хороший уровень знания Java Core. Опыт работы ...,Разрабатывать программное обеспечение (<highli...,backend,"Kotlin backend developer (Java), Java Core, Ko...","Kotlin/Java разработчик, Spring, 3-6 лет, удал...",Опытный Kotlin-разработчик с Java и Spring,Контрактный Kotlin-разработчик с 3-6 годами оп...
3,3,Backend разработчик .NET,Москва,не указано,не указано,не указано,Полная занятость,Удалённо,8 часов,5/2,Более 6 лет,Опыт работы с аналогичным нашему стеком от 6 л...,Проектировать и разрабатывать сервисы с REST A...,backend,"Backend разработчик .NET, C#/.NET, опыт более ...",".NET-разработчик, C#, 6+ лет, удалённо, Москва",Опытный .NET-инженер с C# и масштабируемыми си...,"Главный разработчик .NET с 6+ годами опыта, пр..."
4,4,"Backend-разработчик (Python/TypeScript, Junior)",Москва,80000,RUR,За месяц,Полная занятость,не указано,8 часов,5/2,От 1 года до 3 лет,Хорошее знание Python и/или TypeScript. Опыт р...,Параллельно формируется отдельная ML-команда. ...,backend,Junior Backend-разработчик (Python/TypeScript)...,"Backend-разработчик (Python/TypeScript), опыт ...","Новичок с навыками Python/TypeScript, готов ра...",Разработка backend-части EdTech-платформы с ин...

In [5]:
data.columns

Index(['Unnamed: 0', 'должность', 'город', 'зарплата', 'валюта зарплаты',
       'зарплата за период времени', 'занятость', 'формат работы',
       'часы работы', 'график по дням', 'опыт работы', 'требования',
       'обязанности', 'domen', 'strict', 'normal', 'fuzzy', 'complex'],
      dtype='object')

In [6]:
print(data['strict'].iloc[0])

Backend-разработчик, Python 2+, FastAPI/Django, опыт от 1 до 3 лет, строго на месте работодателя, Зеленоград, зарплата не указана

In [7]:
print(data['normal'].iloc[0])

Backend-разработчик на Python (FastAPI/Django), опыт 1-3 года, на месте, Зеленоград

In [8]:
print(data['fuzzy'].iloc[0])

Опытный разработчик с Python и фреймворками, готов работать в офисе

In [9]:
print(data['complex'].iloc[0])

Разработчик backend-компонентов с опытом 1-3 лет, ответственный за API и поддержку веб-приложений, на месте в Зеленограде

In [10]:
data['должность'].value_counts()

должность
Frontend-разработчик                                                              4
Backend-разработчик                                                               2
Системный аналитик                                                                2
Аналитик со знанием английского языка                                             1
Младший аналитик                                                                  1
Старший системный аналитик                                                        1
Финансовый аналитик Звук Бизнес                                                   1
Аналитик данных                                                                   1
QA инженер (SberDLP)                                                              1
Старший специалист по поддержке HR процессов / Senior Delivery Support Analyst    1
Frontend (JavaScript-разработчик)                                                 1
Аналитик данных (SQL)                                                             1
Middle Frontend-разработчик (React, TypeScript)                                   1
Старший фронтенд разработчик/Senior Frontend Developer                            1
Middle/Middle+ Frontend Developer                                                 1
Frontend-разработчик (React)                                                      1
Senior Frontend Developer (Vue.js)                                                1
IT QA Engineer                                                                    1
Бэкенд разработчик                                                                1
Back-end разработчик C# / .NET                                                    1
Kotlin backend developer (Java)                                                   1
Backend разработчик .NET                                                          1
Backend-разработчик (Python/TypeScript, Junior)                                   1
Backend-developer (Python)                                                        1
Backend-разработчик (Java/Kotlin)                                                 1
Стажёр backend-разработчик в Авито                                                1
QA-инженер/Платежный сервис                                                       1
QA инженер (голосовые сервисы)                                                    1
Инженер по тестированию (QA Engineer)                                             1
QA-инженер (middle)                                                               1
Middle QA тестировщик                                                             1
Лидер центра компетенций QA                                                       1
Стажер по ручному тестированию (QA тестировщик)                                   1
QA инженер                                                                        1
Бизнес-аналитик                                                                   1
Name: count, dtype: int64

In [11]:
data['domen'].value_counts()

domen
backend     11
frontend    11
qa           9
data         9
Name: count, dtype: int64

In [12]:
import re
import pandas as pd

# ==========
# 1) INPUT / OUTPUT PATHS
# ==========
INPUT_PATH = "raw/dataset_kmu.csv"
VACANCIES_OUT = "prepared/vacancies.csv"
QUERIES_OUT = "prepared/queries.csv"

# ==========
# 2) HELPERS
# ==========
def clean_text(x):
    """Удаляет html-подобные теги, лишние пробелы и переводит NaN в пустую строку."""
    if pd.isna(x):
        return ""
    x = str(x)
    x = re.sub(r"<[^>]+>", " ", x)       # убираем теги вроде <highlighttext>
    x = x.replace("\xa0", " ")
    x = re.sub(r"\s+", " ", x).strip()
    return x


# ==========
# 3) READ SOURCE DATA
# ==========
df = pd.read_csv(INPUT_PATH)

# Если есть служебная колонка индекса — удаляем
unnamed_cols = [c for c in df.columns if c.lower().startswith("unnamed")]
if unnamed_cols:
    df = df.drop(columns=unnamed_cols)

# ==========
# 4) CLEAN ALL TEXT COLUMNS
# ==========
for col in df.columns:
    df[col] = df[col].apply(clean_text)

# ==========
# 5) OPTIONAL: MANUAL DOMAIN FIXES
# ==========
# Здесь можно руками поправить явно ошибочные домены по названию вакансии.
# При необходимости просто добавляй новые строки в словарь.
DOMAIN_FIXES = {
    "QA инженер": "qa",
    # "Системный аналитик": "analyst",
    # "Старший системный аналитик": "analyst",
    # "Бизнес-аналитик": "analyst",
    # "Младший аналитик": "analyst",
}

if "должность" in df.columns and "domen" in df.columns:
    df["domen"] = df.apply(
        lambda row: DOMAIN_FIXES.get(row["должность"], row["domen"]),
        axis=1
    )

# ==========
# 6) BUILD VACANCIES TABLE
# ==========
# Переименовываем колонки в более удобный формат
rename_map = {
    "должность": "job_title",
    "город": "city",
    "зарплата": "salary",
    "валюта зарплаты": "salary_currency",
    "зарплата за период времени": "salary_period",
    "занятость": "employment",
    "формат работы": "work_format",
    "часы работы": "work_hours",
    "график по дням": "work_schedule",
    "опыт работы": "experience",
    "требования": "requirements",
    "обязанности": "responsibilities",
    "domen": "domain",
}

vacancies = df.rename(columns=rename_map).copy()

# Добавляем стабильный vacancy_id
vacancies.insert(0, "vacancy_id", [f"VAC_{i:04d}" for i in range(1, len(vacancies) + 1)])

# Оставляем нужные колонки в понятном порядке
vacancy_cols = [
    "vacancy_id",
    "job_title",
    "domain",
    "city",
    "salary",
    "salary_currency",
    "salary_period",
    "employment",
    "work_format",
    "work_hours",
    "work_schedule",
    "experience",
    "requirements",
    "responsibilities",
]

# Оставляем только существующие колонки
vacancy_cols = [c for c in vacancy_cols if c in vacancies.columns]
vacancies = vacancies[vacancy_cols].copy()

# Дополнительно можно убрать совсем пустые строки, если вдруг есть
vacancies = vacancies.drop_duplicates().reset_index(drop=True)

In [13]:
vacancies.columns

Index(['vacancy_id', 'job_title', 'domain', 'city', 'salary',
       'salary_currency', 'salary_period', 'employment', 'work_format',
       'work_hours', 'work_schedule', 'experience', 'requirements',
       'responsibilities'],
      dtype='object')

In [14]:
# ==========
# 7) BUILD QUERIES TABLE
# ==========
query_type_cols = ["strict", "normal", "fuzzy", "complex"]
existing_query_cols = [c for c in query_type_cols if c in df.columns]

queries = (
    vacancies[["vacancy_id", "job_title", "domain"]]
    .join(df[existing_query_cols])
    .melt(
        id_vars=["vacancy_id", "job_title", "domain"],
        value_vars=existing_query_cols,
        var_name="query_type",
        value_name="query_text"
    )
)

# Чистим пустые query
queries["query_text"] = queries["query_text"].apply(clean_text)
queries = queries[queries["query_text"] != ""].copy()

# Добавляем query_id
queries.insert(0, "query_id", [f"Q_{i:05d}" for i in range(1, len(queries) + 1)])

# Упорядочим колонки
query_cols = [
    "query_id",
    "vacancy_id",
    "job_title",
    "domain",
    "query_type",
    "query_text",
]
queries = queries[query_cols].reset_index(drop=True)

In [15]:
vacancies.columns

Index(['vacancy_id', 'job_title', 'domain', 'city', 'salary',
       'salary_currency', 'salary_period', 'employment', 'work_format',
       'work_hours', 'work_schedule', 'experience', 'requirements',
       'responsibilities'],
      dtype='object')

In [16]:
# ==========
# 8) SAVE
# ==========
vacancies.to_csv(VACANCIES_OUT, index=False, encoding="utf-8-sig")
queries.to_csv(QUERIES_OUT, index=False, encoding="utf-8-sig")

# ==========
# 9) QUICK CHECK
# ==========
print("Vacancies shape:", vacancies.shape)
print("Queries shape:", queries.shape)

print("\nVacancies preview:")
print(vacancies.head(3))

print("\nQueries preview:")
print(queries.head(8))

print("\nQuery type distribution:")
print(queries["query_type"].value_counts(dropna=False))

print("\nDomain distribution in vacancies:")
print(vacancies["domain"].value_counts(dropna=False))

Vacancies shape: (40, 14)
Queries shape: (160, 6)

Vacancies preview:
  vacancy_id                        job_title   domain        city  \
0   VAC_0001              Backend-разработчик  backend  Зеленоград
1   VAC_0002               Бэкенд разработчик  backend      Москва
2   VAC_0003  Kotlin backend developer (Java)  backend     Воронеж

       salary salary_currency salary_period        employment  \
0  не указано      не указано    не указано  Полная занятость
1      140000             RUR      За месяц  Полная занятость
2  не указано      не указано    не указано  Полная занятость

             work_format work_hours work_schedule          experience  \
0  На месте работодателя    8 часов           5/2  От 1 года до 3 лет
1       Удалённо, Гибрид    8 часов           5/2  От 1 года до 3 лет
2               Удалённо    8 часов           5/2       От 3 до 6 лет

                                        requirements  \
0  1. Опыт работы с Python от 2х лет. 2. Знание и...
1  Backend : Python, FastAPI / Django / Flask. Fr...
2  Хороший уровень знания Java Core. Опыт работы ...

                                    responsibilities
0  1. Разработка и поддержка backend -компонентов...
1  Разработка и поддержка backend -функционала на...
2  Разрабатывать программное обеспечение ( back -...

Queries preview:
  query_id vacancy_id                                        job_title  \
0  Q_00001   VAC_0001                              Backend-разработчик
1  Q_00002   VAC_0002                               Бэкенд разработчик
2  Q_00003   VAC_0003                  Kotlin backend developer (Java)
3  Q_00004   VAC_0004                         Backend разработчик .NET
4  Q_00005   VAC_0005  Backend-разработчик (Python/TypeScript, Junior)
5  Q_00006   VAC_0006                              Backend-разработчик
6  Q_00007   VAC_0007                       Backend-developer (Python)
7  Q_00008   VAC_0008                Backend-разработчик (Java/Kotlin)

    domain query_type                                         query_text
0  backend     strict  Backend-разработчик, Python 2+, FastAPI/Django...
1  backend     strict  Бэкенд разработчик, Python (FastAPI/Django/Fla...
2  backend     strict  Kotlin backend developer (Java), Java Core, Ko...
3  backend     strict  Backend разработчик .NET, C#/.NET, опыт более ...
4  backend     strict  Junior Backend-разработчик (Python/TypeScript)...
5  backend     strict  Senior Backend-разработчик (Django/DRF, Celery...
6  backend     strict  Junior Backend-разработчик (Python), опыт 0 ле...
7  backend     strict  Backend-разработчик (Java/Kotlin), опыт 3-6 ле...

Query type distribution:
query_type
strict     40
normal     40
fuzzy      40
complex    40
Name: count, dtype: int64

Domain distribution in vacancies:
domain
backend     11
qa          10
frontend    10
data         9
Name: count, dtype: int64

In [11]:
import pandas as pd
bm25_check = pd.read_csv('bm25/retrieval_bm25.csv')
bm25_check.head()

,query_id,candidate_id,search_system,rank,score,latency_ms,retrieved_at
0,Q_00001,C_01209,bm25,1,39.026946,157.871145,2026-03-20T20:16:36.009267
1,Q_00001,C_01096,bm25,2,38.862631,157.871145,2026-03-20T20:16:36.009267
2,Q_00001,C_01663,bm25,3,38.734559,157.871145,2026-03-20T20:16:36.009267
3,Q_00001,C_00031,bm25,4,38.545123,157.871145,2026-03-20T20:16:36.009267
4,Q_00001,C_02030,bm25,5,38.542879,157.871145,2026-03-20T20:16:36.009267

In [12]:
bm25_check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   query_id       2400 non-null   object
 1   candidate_id   2400 non-null   object
 2   search_system  2400 non-null   object
 3   rank           2400 non-null   int64
 4   score          2400 non-null   float64
 5   latency_ms     2400 non-null   float64
 6   retrieved_at   2400 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 131.4+ KB

In [25]:
candidates

,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,last_company,last_job_title,education_level_and_university,resume_updated_at,has_car
0,Мужчина,39,29000,Системный администратор,Советск (Калининградская область),False,False,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,2019-04-16 15:59:00,True
1,Мужчина,60,40000,Технический писатель,Королев,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,2019-04-12 08:42:00,False
2,Женщина,36,20000,Оператор,Тверь,False,False,полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,2019-04-16 08:35:00,False
3,Мужчина,38,100000,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Саратов,False,True,"частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,2019-04-08 14:23:00,False
4,Женщина,26,140000,Региональный менеджер по продажам,Москва,False,True,полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,2019-04-22 10:32:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4946,Мужчина,29,150000,Системный администратор Linux/DevOps,Москва,False,True,полная занятость,полный день,Опыт работы 6 лет 7 месяцев Июнь 2018 — по на...,"ООО ""Спорт-Экспресс Информ""",Системный администратор,Высшее образование 2015 Московский государств...,2019-04-21 22:18:00,True
4947,Женщина,53,20000,Оператор на телефоне,Чебоксары,False,False,частичная занятость,"гибкий график, удаленная работа",Опыт работы 22 года 2 месяца Март 2005 — по н...,Салон красоты АНЮТА,Администратор салона красоты,Среднее специальное образование 1986 Строитель...,2019-04-18 21:08:00,False
4948,Мужчина,22,100000,Тестировщик на проникновение / Тестировщик вэб...,Москва,False,False,полная занятость,"гибкий график, полный день",Опыт работы 3 месяца Июнь 2017 — Август 2017...,"ООО ""ГНСС плюс""",Технический специалист,Высшее образование (Магистр) 2019 University o...,2019-04-19 18:33:00,True
4949,Мужчина,38,170000,руководитель ИТ-подразделения,Казань,True,True,полная занятость,полный день,Опыт работы 16 лет 9 месяцев Март 2017 — по н...,ICL-КПО ВС,Системный архитектор / заместитель техническог...,Высшее образование 2003 Казанский национальны...,2019-05-07 11:54:00,False
4950,Мужчина,23,50000,Менеджер проектов,Москва,False,False,"стажировка, проектная работа, полная занятость","гибкий график, полный день, сменный график, уд...",Опыт работы 1 год 10 месяцев Октябрь 2018 — п...,Экспримо,Проектный менеджер,Неоконченное высшее образование 2018 Военный ...,2019-04-17 10:42:00,False

# vector retrieval

In [36]:
queries = pd.read_csv('prepared/queries.csv')
vacancies = pd.read_csv('prepared/vacancies.csv')
candidates = pd.read_csv('raw/candidates.csv')

In [37]:
queries.columns

Index(['query_id', 'vacancy_id', 'job_title', 'domain', 'query_type',
       'query_text'],
      dtype='object')

In [38]:
vacancies.columns

Index(['vacancy_id', 'job_title', 'domain', 'city', 'salary',
       'salary_currency', 'salary_period', 'employment', 'work_format',
       'work_hours', 'work_schedule', 'experience', 'requirements',
       'responsibilities'],
      dtype='object')

In [39]:
candidates.columns

Index(['candidate_id', 'sex', 'age', 'expected_salary_rub', 'desired_position',
       'city', 'ready_to_relocate', 'ready_for_business_trips',
       'employment_type', 'work_schedule', 'work_experience', 'last_company',
       'last_job_title', 'education_level_and_university', 'resume_updated_at',
       'has_car'],
      dtype='object')

In [16]:
queries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   query_id    160 non-null    object
 1   vacancy_id  160 non-null    object
 2   job_title   160 non-null    object
 3   domain      160 non-null    object
 4   query_type  160 non-null    object
 5   query_text  160 non-null    object
dtypes: object(6)
memory usage: 7.6+ KB

In [17]:
vacancies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   vacancy_id        40 non-null     object
 1   job_title         40 non-null     object
 2   domain            40 non-null     object
 3   city              40 non-null     object
 4   salary            36 non-null     object
 5   salary_currency   40 non-null     object
 6   salary_period     40 non-null     object
 7   employment        40 non-null     object
 8   work_format       40 non-null     object
 9   work_hours        40 non-null     object
 10  work_schedule     40 non-null     object
 11  experience        40 non-null     object
 12  requirements      39 non-null     object
 13  responsibilities  39 non-null     object
dtypes: object(14)
memory usage: 4.5+ KB

In [40]:
candidates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4951 entries, 0 to 4950
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   candidate_id                    4951 non-null   object
 1   sex                             4951 non-null   object
 2   age                             4951 non-null   int64
 3   expected_salary_rub             4951 non-null   int64
 4   desired_position                4951 non-null   object
 5   city                            4951 non-null   object
 6   ready_to_relocate               4853 non-null   object
 7   ready_for_business_trips        4939 non-null   object
 8   employment_type                 4951 non-null   object
 9   work_schedule                   4951 non-null   object
 10  work_experience                 4928 non-null   object
 11  last_company                    4951 non-null   object
 12  last_job_title                  4951 non-null   object
 13  education_level_and_university  4951 non-null   object
 14  resume_updated_at               4951 non-null   object
 15  has_car                         4951 non-null   bool
dtypes: bool(1), int64(2), object(13)
memory usage: 585.2+ KB

In [41]:
candidates.head(2).to_dict()

{'candidate_id': {0: 'C_00001', 1: 'C_00002'},
 'sex': {0: 'Мужчина', 1: 'Мужчина'},
 'age': {0: 39, 1: 60},
 'expected_salary_rub': {0: 29000, 1: 40000},
 'desired_position': {0: 'Системный администратор', 1: 'Технический писатель'},
 'city': {0: 'Советск (Калининградская область)', 1: 'Королев'},
 'ready_to_relocate': {0: False, 1: False},
 'ready_for_business_trips': {0: False, 1: True},
 'employment_type': {0: 'частичная занятость, проектная работа, полная занятость',
  1: 'частичная занятость, проектная работа, полная занятость'},
 'work_schedule': {0: 'гибкий график, полный день, сменный график, вахтовый метод, удаленная работа',
  1: 'гибкий график, полный день, сменный график, удаленная работа'},
 'work_experience': {0: 'Опыт работы 16 лет 10 месяцев  Август 2010 — по настоящее время 8 лет 10 месяцев МАОУ "СОШ № 1 г.Немана" Системный администратор Обслуживание ПК,установка ПО, ремонт, периферийной техники, Интернет локальная сеть. Ведение Электронного журнала, сайта организации.  Август 2002 — Август  2010 8 лет 1 месяц ТС "ВЕСТЕР-ИНФО" Старший продавец, директор отдела Продажи компьютерной техники',
  1: 'Опыт работы 19 лет 5 месяцев  Январь 2000 — по настоящее время 19 лет 5 месяцев Временный трудовой коллектив Москва Информационные технологии, системная интеграция, интернет ... Разработка программного обеспечения Системная интеграция, автоматизации технологических и бизнес-процессов предприятия, ИТ-консалтинг Менеджер проекта, Аналитик, Технический писатель Весь цикл ПО, кроме программирования.'},
 'last_company': {0: 'МАОУ "СОШ № 1 г.Немана"',
  1: 'Временный трудовой коллектив'},
 'last_job_title': {0: 'Системный администратор',
  1: 'Менеджер проекта, Аналитик, Технический писатель'},
 'education_level_and_university': {0: 'Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота, Калининград судоводительский, Организация и безопасность движения',
  1: 'Высшее образование 1981  Военно-космическая академия им. А.Ф. Можайского, Санкт-Петербург АСУ, АСУ'},
 'resume_updated_at': {0: '2019-04-16 15:59:00', 1: '2019-04-12 08:42:00'},
 'has_car': {0: True, 1: False}}

# judgment

In [75]:
import pandas as pd

In [76]:
judgments = pd.read_csv('llm_judge/judgments.csv')
candidates = pd.read_csv('raw/candidates.csv')
queries = pd.read_csv('prepared/queries.csv')
vacancies = pd.read_csv('prepared/vacancies.csv')

In [92]:
candidates

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,has_car,full_resume
0,C_00001,Мужчина,39,29000,Системный администратор,Советск (Калининградская область),не готов к переезду,не готов к командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,16.833333,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,есть машина,Желаемая позиция: Системный администратор Посл...
1,C_00002,Мужчина,60,40000,Технический писатель,Королев,не готов к переезду,готов к командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,19.416667,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,нет машины,Желаемая позиция: Технический писатель Последн...
2,C_00003,Женщина,36,20000,Оператор,Тверь,не готов к переезду,не готов к командировкам,полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,10.250000,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,нет машины,Желаемая позиция: Оператор Последняя должность...
3,C_00004,Мужчина,38,100000,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,Саратов,не готов к переезду,готов к командировкам,"частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,18.750000,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,нет машины,Желаемая позиция: Веб-разработчик (HTML / CSS ...
4,C_00005,Женщина,26,140000,Региональный менеджер по продажам,Москва,не готов к переезду,готов к командировкам,полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,5.583333,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,нет машины,Желаемая позиция: Региональный менеджер по про...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44739,C_44740,Мужчина,30,50000,"Финансист, аналитик, экономист, бухгалтер, мен...",Тверь,готов к переезду,готов к командировкам,полная занятость,"полный день, удаленная работа","Опыт работы 7 лет 7 месяцев Финансист, аналит...",7.583333,"ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,Высшее образование 2015 Московский гуманитарн...,нет машины,"Желаемая позиция: Финансист, аналитик, экономи..."
44740,C_44741,Мужчина,27,39000,"Системный администратор, IT-специалист",Липецк,готов к переезду,готов к командировкам,"проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...","Опыт работы 7 лет Системный администратор, IT...",7.000000,ИП Пестрецов,Предприниматель,Высшее образование (Бакалавр) 2016 Воронежски...,нет машины,"Желаемая позиция: Системный администратор, IT-..."
44741,C_44742,Женщина,48,40000,"Аналитик данных, Математик",Челябинск,готов к переезду,готов к командировкам,полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,21.416667,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,нет машины,"Желаемая позиция: Аналитик данных, Математик П..."
44742,C_44743,Мужчина,24,20000,Контент-менеджер,Тамбов,не готов к переезду,не готов к командировкам,"частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,3.833333,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,есть машина,Желаемая позиция: Контент-менеджер Последняя д...
44743,C_44744,Мужчина,38,120000,Руководитель проекта,Москва,не готов к переезду,не готов к командировкам,полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,15.833333,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,нет машины,Желаемая позиция: Руководитель проекта Последн...

In [77]:
candidates['ready_to_relocate'] = candidates['ready_to_relocate'].apply(lambda x: 'не готов к переезду' if not x else 'готов к переезду')
candidates['ready_for_business_trips'] = candidates['ready_for_business_trips'].apply(lambda x: 'не готов к командировкам' if not x else 'готов к командировкам')
candidates['has_car'] = candidates['has_car'].apply(lambda x: 'нет машины' if not x else 'есть машина')
candidates = candidates.drop('resume_updated_at', axis=1)


def safe_bool_text(x, true_text, false_text, na_text='не указано'):
    if pd.isna(x):
        return na_text
    return true_text if bool(x) else false_text

def create_full_profile(row):
    parts = [
        f"Желаемая позиция: {row.get('desired_position', 'не указано')}",
        f"Последняя должность: {row.get('last_job_title', 'не указано')}",
        f"Последняя компания: {row.get('last_company', 'не указано')}",
        f"Город: {row.get('city', 'не указано')}",
        f"Тип занятости: {row.get('employment_type', 'не указано')}",
        f"График работы: {row.get('work_schedule', 'не указано')}",
        f"Ожидаемая зарплата: {row.get('expected_salary_rub', 'не указано')} руб.",
        f"Готовность к переезду: {safe_bool_text(row.get('ready_to_relocate'), 'готов к переезду', 'не готов к переезду')}",
        f"Готовность к командировкам: {safe_bool_text(row.get('ready_for_business_trips'), 'готов к командировкам', 'не готов к командировкам')}",
        f"Образование: {row.get('education_level_and_university', 'не указано')}",
        f"Опыт работы: {row.get('work_experience', 'не указано')}",
    ]
    return " ".join(map(str, parts))

candidates['full_resume'] = candidates.apply(create_full_profile, axis=1)

In [78]:
bm25 = pd.read_csv('bm25/retrieval_bm25.csv')
sql_hr = pd.read_csv('sql-hr/retrieval_sql_hr.csv')
embedd = pd.read_csv('emb/retrieval_vector.csv')


retrieval_results = pd.concat([bm25, sql_hr, embedd], join='inner')
retrieval_results.drop_duplicates(subset=['query_id', 'candidate_id'], keep='first', inplace=True)

In [79]:
retrieval_results.head(1)

,query_id,candidate_id,search_system,rank,score,latency_ms,retrieved_at
0,Q_00001,C_37247,bm25,1,0.364034,596.772841,2026-03-29T21:12:23.995159

In [80]:
quieries = pd.read_csv('prepared/queries.csv')

In [81]:
# 1. Считаем длину текста в символах
lengths = quieries['query_text'].str.len()

# 2. Считаем квартили
q1 = lengths.quantile(0.25) # Конец "коротких"
q3 = lengths.quantile(0.75) # Начало "длинных"
iqr = q3 - q1               # Сам интерквартильный размах

print(f"Граница коротких (Q1): {q1} симв.")
print(f"Медиана (Q2): {lengths.median()} симв.")
print(f"Граница длинных (Q3): {q3} симв.")
print(f"IQR: {iqr}")

Граница коротких (Q1): 100.0 симв.
Медиана (Q2): 130.0 симв.
Граница длинных (Q3): 177.25 симв.
IQR: 77.25

In [82]:
quieries['query_length_bucket'] = quieries['query_text'].apply(lambda x: 'short' if len(x) < 100 else 'medium' if 100 <= len(x) <= 170 else 'long')

In [83]:
def get_balanced_gold_subset(df, target_counts):
    df = df.copy()
    gold_indices = []

    for q_type, total_needed in target_counts.items():
        # Все запросы нужного типа (например, 'strict')
        type_subset = df[df['query_type'] == q_type]

        # 1. Пытаемся взять равномерно по длинам
        lengths = ['short', 'medium', 'long']
        per_length = total_needed // 3

        type_selected_indices = []

        for length in lengths:
            pool = type_subset[type_subset['query_length_bucket'] == length]
            # Берем сколько нужно, но не больше, чем есть в наличии
            n = min(len(pool), per_length)
            if n > 0:
                selected = pool.sample(n=n, random_state=42)
                type_selected_indices.extend(selected.index.tolist())

        # 2. Если после этого набрали меньше, чем total_needed (например, не хватило 'long')
        # Добираем остаток из всех оставшихся запросов этого ТИПА (любой длины)
        remaining_needed = total_needed - len(type_selected_indices)
        if remaining_needed > 0:
            # Исключаем тех, кого уже выбрали
            remaining_pool = type_subset.drop(type_selected_indices)
            n_extra = min(len(remaining_pool), remaining_needed)
            if n_extra > 0:
                extra_selected = remaining_pool.sample(n=n_extra, random_state=42)
                type_selected_indices.extend(extra_selected.index.tolist())

        gold_indices.extend(type_selected_indices)

    # Ставим флаг
    df['is_gold'] = False
    # Используем list(set()), чтобы точно не было дублей в индексах
    df.loc[list(set(gold_indices)), 'is_gold'] = True

    return df

# Твои цели из ТЗ
targets = {
    'strict': 8,
    'normal': 16,
    'fuzzy': 8,
    'complex': 8
}

gold_dataset = get_balanced_gold_subset(quieries, targets)

In [84]:
gold_dataset.shape

(160, 8)

In [85]:
# Фильтруем только голд и смотрим пересечение типа и длины
gold_dataset = gold_dataset[gold_dataset['is_gold']== True]

In [86]:
gold_dataset

,query_id,vacancy_id,job_title,domain,query_type,query_text,query_length_bucket,is_gold
0,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True
3,Q_00004,VAC_0004,Backend разработчик .NET,backend,strict,"Backend разработчик .NET, C#/.NET, опыт более ...",short,True
4,Q_00005,VAC_0005,"Backend-разработчик (Python/TypeScript, Junior)",backend,strict,Junior Backend-разработчик (Python/TypeScript)...,long,True
14,Q_00015,VAC_0015,Лидер центра компетенций QA,qa,strict,"Лидер центра компетенций QA, опыт 3-6 лет, Мос...",long,True
17,Q_00018,VAC_0018,QA инженер (голосовые сервисы),qa,strict,"QA-инженер для голосовых сервисов, опыт 1-3 го...",long,True
28,Q_00029,VAC_0029,Frontend-разработчик,frontend,strict,"Frontend-разработчик, Vue 3 (Pinia, Vue Router...",long,True
30,Q_00031,VAC_0031,Старший специалист по поддержке HR процессов /...,data,strict,"Старший специалист по HR-процессам, опыт в отд...",medium,True
31,Q_00032,VAC_0032,Системный аналитик,backend,strict,"Системный аналитик, опыт с Jira, Confluence, G...",medium,True
40,Q_00041,VAC_0001,Backend-разработчик,backend,normal,Backend-разработчик на Python (FastAPI/Django)...,short,True
41,Q_00042,VAC_0002,Бэкенд разработчик,backend,normal,Backend-разработчик на Python (FastAPI/Django)...,medium,True
50,Q_00051,VAC_0011,QA-инженер/Платежный сервис,qa,normal,"QA-инженер, опыт 3-6 лет, высшее образование, ...",short,True
51,Q_00052,VAC_0012,Инженер по тестированию (QA Engineer),qa,normal,"QA-инженер, опыт 3-6 лет, тестирование програм...",medium,True
54,Q_00055,VAC_0015,Лидер центра компетенций QA,qa,normal,"Лидер QA, опыт 3-6 лет, Москва, тестирование п...",medium,True
56,Q_00057,VAC_0017,QA инженер,qa,normal,QA-тестировщик с опытом работы в коммерческих ...,medium,True
58,Q_00059,VAC_0019,IT QA Engineer,qa,normal,QA-инженер с опытом тестирования веб-приложени...,medium,True
61,Q_00062,VAC_0022,Frontend-разработчик (React),frontend,normal,"React-разработчик, опыт 3-6 лет, знание JS, CS...",short,True
62,Q_00063,VAC_0023,Middle/Middle+ Frontend Developer,frontend,normal,"Frontend-разработчик на React/Next.js, опыт 3-...",short,True
63,Q_00064,VAC_0024,Старший фронтенд разработчик/Senior Frontend D...,frontend,normal,"Старший фронтенд-разработчик на Vue.js, опыт 6...",short,True
66,Q_00067,VAC_0027,Frontend (JavaScript-разработчик),frontend,normal,"JavaScript-разработчик (React, Redux), опыт 3-...",short,True
68,Q_00069,VAC_0029,Frontend-разработчик,frontend,normal,"Frontend-разработчик на Vue.js и Node.js, опыт...",medium,True
71,Q_00072,VAC_0032,Системный аналитик,backend,normal,"Системный аналитик с опытом работы в Jira, Con...",medium,True
76,Q_00077,VAC_0037,Аналитик со знанием английского языка,data,normal,"Аналитик на английском, Москва, полная занятос...",long,True
77,Q_00078,VAC_0038,Системный аналитик,data,normal,"Системный аналитик, Москва, гибрид, опыт от 1 ...",medium,True
78,Q_00079,VAC_0039,Аналитик данных (SQL),data,normal,"Аналитик данных (SQL), Москва, на месте, 8 час...",medium,True
84,Q_00085,VAC_0005,"Backend-разработчик (Python/TypeScript, Junior)",backend,fuzzy,"Новичок с навыками Python/TypeScript, готов ра...",medium,True
87,Q_00088,VAC_0008,Backend-разработчик (Java/Kotlin),backend,fuzzy,Опытный Java/Kotlin-разработчик с навыками мик...,medium,True
90,Q_00091,VAC_0011,QA-инженер/Платежный сервис,qa,fuzzy,"Эксперт в тестировании с опытом 3 лет, готов к...",short,True
96,Q_00097,VAC_0017,QA инженер,qa,fuzzy,"Эксперт в тестировании веб-приложений, готов а...",medium,True
103,Q_00104,VAC_0024,Старший фронтенд разработчик/Senior Frontend D...,frontend,fuzzy,"Эксперт в Vue.js с опытом старших ролей, готов...",short,True
110,Q_00111,VAC_0031,Старший специалист по поддержке HR процессов /...,data,fuzzy,Эксперт в HR-процессах с опытом работы в отдел...,medium,True
114,Q_00115,VAC_0035,Старший системный аналитик,data,fuzzy,Системный аналитик с опытом в разработке бизне...,short,True
119,Q_00120,VAC_0040,Бизнес-аналитик,data,fuzzy,"Специалист с опытом в IT-аналитике, умение раб...",medium,True
120,Q_00121,VAC_0001,Backend-разработчик,backend,complex,Разработчик backend-компонентов с опытом 1-3 л...,medium,True
121,Q_00122,VAC_0002,Бэкенд разработчик,backend,complex,"Бэкенд-разработчик с опытом 1-3 лет, интеграци...",short,True
126,Q_00127,VAC_0007,Backend-developer (Python),backend,complex,Разработка backend-части с использованием Pyth...,medium,True
136,Q_00137,VAC_0017,QA инженер,qa,complex,QA-инженер для тестирования frontend/backend-с...,long,True
137,Q_00138,VAC_0018,QA инженер (голосовые сервисы),qa,complex,QA-инженер для разработки методики тестировани...,long,True
148,Q_00149,VAC_0029,Frontend-разработчик,frontend,complex,Главный фронтенд-разработчик для проекта разра...,long,True
150,Q_00151,VAC_0031,Старший специалист по поддержке HR процессов /...,data,complex,Старший специалист по поддержке HR-процессов с...,long,True
157,Q_00158,VAC_0038,Системный аналитик,data,complex,Системный аналитик с опытом разработки требова...,long,True

In [87]:
gold_dataset

,query_id,vacancy_id,job_title,domain,query_type,query_text,query_length_bucket,is_gold
0,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True
3,Q_00004,VAC_0004,Backend разработчик .NET,backend,strict,"Backend разработчик .NET, C#/.NET, опыт более ...",short,True
4,Q_00005,VAC_0005,"Backend-разработчик (Python/TypeScript, Junior)",backend,strict,Junior Backend-разработчик (Python/TypeScript)...,long,True
14,Q_00015,VAC_0015,Лидер центра компетенций QA,qa,strict,"Лидер центра компетенций QA, опыт 3-6 лет, Мос...",long,True
17,Q_00018,VAC_0018,QA инженер (голосовые сервисы),qa,strict,"QA-инженер для голосовых сервисов, опыт 1-3 го...",long,True
28,Q_00029,VAC_0029,Frontend-разработчик,frontend,strict,"Frontend-разработчик, Vue 3 (Pinia, Vue Router...",long,True
30,Q_00031,VAC_0031,Старший специалист по поддержке HR процессов /...,data,strict,"Старший специалист по HR-процессам, опыт в отд...",medium,True
31,Q_00032,VAC_0032,Системный аналитик,backend,strict,"Системный аналитик, опыт с Jira, Confluence, G...",medium,True
40,Q_00041,VAC_0001,Backend-разработчик,backend,normal,Backend-разработчик на Python (FastAPI/Django)...,short,True
41,Q_00042,VAC_0002,Бэкенд разработчик,backend,normal,Backend-разработчик на Python (FastAPI/Django)...,medium,True
50,Q_00051,VAC_0011,QA-инженер/Платежный сервис,qa,normal,"QA-инженер, опыт 3-6 лет, высшее образование, ...",short,True
51,Q_00052,VAC_0012,Инженер по тестированию (QA Engineer),qa,normal,"QA-инженер, опыт 3-6 лет, тестирование програм...",medium,True
54,Q_00055,VAC_0015,Лидер центра компетенций QA,qa,normal,"Лидер QA, опыт 3-6 лет, Москва, тестирование п...",medium,True
56,Q_00057,VAC_0017,QA инженер,qa,normal,QA-тестировщик с опытом работы в коммерческих ...,medium,True
58,Q_00059,VAC_0019,IT QA Engineer,qa,normal,QA-инженер с опытом тестирования веб-приложени...,medium,True
61,Q_00062,VAC_0022,Frontend-разработчик (React),frontend,normal,"React-разработчик, опыт 3-6 лет, знание JS, CS...",short,True
62,Q_00063,VAC_0023,Middle/Middle+ Frontend Developer,frontend,normal,"Frontend-разработчик на React/Next.js, опыт 3-...",short,True
63,Q_00064,VAC_0024,Старший фронтенд разработчик/Senior Frontend D...,frontend,normal,"Старший фронтенд-разработчик на Vue.js, опыт 6...",short,True
66,Q_00067,VAC_0027,Frontend (JavaScript-разработчик),frontend,normal,"JavaScript-разработчик (React, Redux), опыт 3-...",short,True
68,Q_00069,VAC_0029,Frontend-разработчик,frontend,normal,"Frontend-разработчик на Vue.js и Node.js, опыт...",medium,True
71,Q_00072,VAC_0032,Системный аналитик,backend,normal,"Системный аналитик с опытом работы в Jira, Con...",medium,True
76,Q_00077,VAC_0037,Аналитик со знанием английского языка,data,normal,"Аналитик на английском, Москва, полная занятос...",long,True
77,Q_00078,VAC_0038,Системный аналитик,data,normal,"Системный аналитик, Москва, гибрид, опыт от 1 ...",medium,True
78,Q_00079,VAC_0039,Аналитик данных (SQL),data,normal,"Аналитик данных (SQL), Москва, на месте, 8 час...",medium,True
84,Q_00085,VAC_0005,"Backend-разработчик (Python/TypeScript, Junior)",backend,fuzzy,"Новичок с навыками Python/TypeScript, готов ра...",medium,True
87,Q_00088,VAC_0008,Backend-разработчик (Java/Kotlin),backend,fuzzy,Опытный Java/Kotlin-разработчик с навыками мик...,medium,True
90,Q_00091,VAC_0011,QA-инженер/Платежный сервис,qa,fuzzy,"Эксперт в тестировании с опытом 3 лет, готов к...",short,True
96,Q_00097,VAC_0017,QA инженер,qa,fuzzy,"Эксперт в тестировании веб-приложений, готов а...",medium,True
103,Q_00104,VAC_0024,Старший фронтенд разработчик/Senior Frontend D...,frontend,fuzzy,"Эксперт в Vue.js с опытом старших ролей, готов...",short,True
110,Q_00111,VAC_0031,Старший специалист по поддержке HR процессов /...,data,fuzzy,Эксперт в HR-процессах с опытом работы в отдел...,medium,True
114,Q_00115,VAC_0035,Старший системный аналитик,data,fuzzy,Системный аналитик с опытом в разработке бизне...,short,True
119,Q_00120,VAC_0040,Бизнес-аналитик,data,fuzzy,"Специалист с опытом в IT-аналитике, умение раб...",medium,True
120,Q_00121,VAC_0001,Backend-разработчик,backend,complex,Разработчик backend-компонентов с опытом 1-3 л...,medium,True
121,Q_00122,VAC_0002,Бэкенд разработчик,backend,complex,"Бэкенд-разработчик с опытом 1-3 лет, интеграци...",short,True
126,Q_00127,VAC_0007,Backend-developer (Python),backend,complex,Разработка backend-части с использованием Pyth...,medium,True
136,Q_00137,VAC_0017,QA инженер,qa,complex,QA-инженер для тестирования frontend/backend-с...,long,True
137,Q_00138,VAC_0018,QA инженер (голосовые сервисы),qa,complex,QA-инженер для разработки методики тестировани...,long,True
148,Q_00149,VAC_0029,Frontend-разработчик,frontend,complex,Главный фронтенд-разработчик для проекта разра...,long,True
150,Q_00151,VAC_0031,Старший специалист по поддержке HR процессов /...,data,complex,Старший специалист по поддержке HR-процессов с...,long,True
157,Q_00158,VAC_0038,Системный аналитик,data,complex,Системный аналитик с опытом разработки требова...,long,True

In [88]:
pooled_candidates = pd.merge(gold_dataset, retrieval_results, how='left', on='query_id')

In [89]:
pooled_candidates.head(2)

,query_id,vacancy_id,job_title,domain,query_type,query_text,query_length_bucket,is_gold,candidate_id,search_system,rank,score,latency_ms,retrieved_at
0,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True,C_37247,bm25,1,0.364034,596.772841,2026-03-29T21:12:23.995159
1,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True,C_30277,bm25,2,0.363219,596.772841,2026-03-29T21:12:23.995159

In [90]:
pooled_candidates_to_judge_res = pd.merge(pooled_candidates, candidates[['candidate_id', 'full_resume']], how='left', on='candidate_id')

In [91]:
pooled_candidates_to_judge_res.head(2)

,query_id,vacancy_id,job_title,domain,query_type,query_text,query_length_bucket,is_gold,candidate_id,search_system,rank,score,latency_ms,retrieved_at,full_resume
0,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True,C_37247,bm25,1,0.364034,596.772841,2026-03-29T21:12:23.995159,"Желаемая позиция: Руководитель направления, Ар..."
1,Q_00001,VAC_0001,Backend-разработчик,backend,strict,"Backend-разработчик, Python 2+, FastAPI/Django...",medium,True,C_30277,bm25,2,0.363219,596.772841,2026-03-29T21:12:23.995159,Желаемая позиция: Главный специалист (Разработ...

In [64]:
candidates[candidates['candidate_id'] == 'C_30277']

,candidate_id,sex,age,expected_salary_rub,desired_position,city,ready_to_relocate,ready_for_business_trips,employment_type,work_schedule,work_experience,work_experience_years,last_company,last_job_title,education_level_and_university,has_car,full_resume
30276,C_30277,Мужчина,34,200000,Главный специалист (Разработчик и администрато...,Москва,готов к переезду,готов к командировкам,полная занятость,"удаленная работа, гибкий график, полный день",Опыт работы 9 лет 3 месяца Главный специалист...,9.25,Ulysta Software und Consulting GmbH,Ведущий инженер-программист,Высшее образование 2008 Самарский государстве...,нет машины,ожидаю зп 200000 готов к переезду готов к ком...

In [5]:
import pandas as pd
judge_input = pd.read_csv('llm_judge/judge_input.csv')
judge_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1759 entries, 0 to 1758
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   query_id       1759 non-null   object
 1   vacancy_id     1759 non-null   object
 2   job_title      1759 non-null   object
 3   domain         1759 non-null   object
 4   query_type     1759 non-null   object
 5   query_text     1759 non-null   object
 6   is_gold        1759 non-null   bool
 7   candidate_id   1759 non-null   object
 8   search_system  1759 non-null   object
 9   rank           1759 non-null   int64
 10  score          1759 non-null   float64
 11  latency_ms     1759 non-null   float64
 12  retrieved_at   1759 non-null   object
 13  full_resume    1759 non-null   object
dtypes: bool(1), float64(2), int64(1), object(10)
memory usage: 180.5+ KB

In [6]:
import pandas as pd
judgments_raw = pd.read_csv('llm_judge/judgments_raw.csv')
judgments_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   query_id         1725 non-null   object
 1   candidate_id     1725 non-null   object
 2   relevance_score  1725 non-null   int64
 3   search_system    1725 non-null   object
 4   judge_model      1725 non-null   object
 5   judge_prompt     1725 non-null   object
 6   judge_comment    1725 non-null   object
dtypes: int64(1), object(6)
memory usage: 94.5+ KB